### ISSUE TITLE
The unzip command cannot handle zips within zips

### ISSUE THREAD

**Issue by NicEastvillage** [RLBot/AutoLeaguePlay#23]

**Comment by tarehart** [comment]
Does it need to? I'm expecting the user to manually unzip the Google drive download into the bots folder, then run the unzip command to find the nested ones.

Is there an individual bot submission with nested zips?

**Comment by NicEastvillage** [comment]
Oh, true, it might not be needed if we just unzip the downloaded zip from the drive. But I have a follow up question then; what is your process for downloading a the drive and extracting?

**Comment by tarehart** [comment]
I delete everything in the bots folder, then download from drive into my downloads folder, then extract into the bots folder using 7-zip.

I've noticed that 7-zip preserves timestamps by default.

**Comment by skyborgff** [comment]
Windows natively supports .zip, do you know if that still preserves timestamps?

**Comment by tarehart** [comment]
I'm 65% sure it does not

**Comment by NicEastvillage** [comment]
Slightly related; In the LeaguePlay submission folder Levi is currently in a rar file. We should unzip those as well.
